# This is a basic workflow to help you get started with Actions

name: Process GP Election Model

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Checkout Repo
      uses: actions/checkout@v1
   
    - name: Process Model
      run: |
        conda activate base
        python 1-Data-step.py

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}

    - name: Stop AWS EC2
      run: |
        #aws ec2 stop-instances --instance-ids i-0c3edd98087da7524 | at now + 1 minute
