
name: Start AWS EC2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Start AWS VM
      run: |
        aws ec2 start-instances --instance-ids i-0c3edd98087da7524
        
    - name: Repository Dispatch (Trigger Model Run)
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.token }}
        event-type: trigger-model
